[tool.poetry]
name = "examplepackage"
version = "0.1.0"
description = "A simple example package"
authors = ["Guangya Liu <gyliu@ibm.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
