[project]
name = "langgraph-memory-demo"
version = "0.1.0"
description = "LangGraph in-memory saver demo"
requires-python = ">=3.9"
dependencies = [
    "langgraph",
    "langchain-google-genai",
    "langchain-community",
    "duckduckgo-search",
]

[tool.uv]
dev-dependencies = [] 