apiVersion: v1
kind: Namespace
metadata:
  name: llm-d
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa
  namespace: llm-d
  labels:
    app.kubernetes.io/part-of: llm-d
automountServiceAccountToken: false
