##
# This docker-compose is used for developing Weaviate, i.e. for contributors. 
# THIS IS NOT INTENDED FOR USERS !!
#
# To get a docker-compose file to run Weaviate, please follow the instructions at
# https://weaviate.io/developers/weaviate/installation/docker-compose
##
version: '3.4'
services:
  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.24.1
    ports:
    - 8080:8080
    - 50051:50051
    volumes:
    - ./tools/dev/weaviate_data:/var/lib/weaviate
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      ENABLE_MODULES: 'text2vec-cohere,text2vec-huggingface,text2vec-palm,text2vec-openai,generative-openai,generative-cohere,generative-palm,ref2vec-centroid,reranker-cohere,qna-openai'
      CLUSTER_HOSTNAME: 'node1'
  contextionary:
    image: semitechnologies/contextionary:en0.16.0-v1.2.1
    ports:
      - "9999:9999"
    environment:
      EXTENSIONS_STORAGE_MODE: weaviate
#      EXTENSIONS_STORAGE_ORIGIN: http://host.docker.internal:8080
      OCCURRENCE_WEIGHT_LINEAR_FACTOR: 0.75
      LOG_LEVEL: debug
  prometheus:
    image: prom/prometheus:v2.46.0
    volumes:
      - ./tools/dev/prometheus_config/:/etc/prometheus/
      - ./data/prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - "9099:9090"
