apiVersion: batch/v1
kind: Job
metadata:
  name: elastic-job-team-a
  namespace: fairshare-team-a
  labels:
    kueue.x-k8s.io/queue-name: lq-team-a
  annotations:
    # PartialAdmission：最少 2 个 pod，最多 10 个 pod
    kueue.x-k8s.io/job-min-parallelism: "2"
spec:
  parallelism: 10         # 弹性上限：最多希望运行 10 个 pod（10 CPU）
  completions: 10
  suspend: true
  template:
    metadata:
      labels:
        app: elastic-job-team-a
    spec:
      restartPolicy: Never
      containers:
        - name: worker
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              echo "TEAM-A worker started, pod=$(hostname)"
              sleep 300
              echo "TEAM-A worker done"
          resources:
            requests:
              cpu: "1"
              memory: "256Mi"
            limits:
              cpu: "1"
              memory: "256Mi"
